version: '3'
services:
  web:
    build: .
    container_name: sqlhasherapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - webnet
networks:
  webnet:
